# Version of Docker-compose
version: "3.9"
services:
  # Add the node-js service
  node:
  # Location to the node.js dockerfile
    build: 
      context: ./server
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: node-container
    image: unistart:backend-arm-latest
    ports:
        # Host port:Container port
      - '8123:8000'
  react:
  # Location to the react.js dockerfile
    build: 
      context: ./client
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: react-container
    image: unistart:frontend-arm-latest
    ports:
      # Host port:Container port
      - '3123:3000'